#+TITLE: Work Logs of Nikhil
#+AUTHOR: VLEAD
#+DATE: [2017-11-30 Thu]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction
  All my work logs are collated here.

* Work Log of Nikhil
** Week 1 [2017-11-27 Mon] to [2017-12-03 Sun]
   + [2017-11-27 Mon] - Explored the vlabs.ac.in and got to know about the project
   + [2017-11-28 Tue] - Worked on installation of college cloud Using given documentation. 
     Environmental setup has been done. written a report on documentation. Reviewed the files in expt6 of Responsive lab.
     noticed a small errors like spoon_fill which deviates from beaker.it was corrected by replacing the left(style) to 13% in #spoonfill.
     exploration of expt6 is done
   + [2017-11-29 Wed] -  new work(computer organisation lab as been alloted).have got three 3 experiments to review if there are any errors.
     exp1 as been explored . beautifying of the codes(indentation of html,css,js) as been done .tried finding any errors in the code.exp1 is ready for production
   + [2017-11-30 Thurs] - beautification of codes has been done and noticed small errors but for fixing them i had studied the experiment details and topics and later 
     understood the code of exp2
** Week 2 [2017-12-04 Mon] to [2017-12-08 Fri]
   + [2017-12-04 Mon] - explored through some topics needed for that experiment(exp2) and couldnt get it with that .tested the experiment and found some errors and tried to fix them.
     went through issues of physical chemistry lab.
   + [2017-12-05 Tue] - exp2 of computer organisation is completed almost and committed it for testing the labs of exp1,exp2(except the floating part of exp2) of computer organization
   + [2017-12-06 Wed] - explored through exp9 of computer organization but couldnt get any idea how to implement .explored through the references too but it didnt help me in get the functionality
     or code of exp9.
   + [2017-12-07 Thurs] - again tried exploring the same lab upto afternoon but no improvement. issue was informed to mentor.
   + [2017-12-08 Fri] - Two labs (molecular spectroscopy and molecular flourescense) labs have been alloted to check the problem of the code differing on localserver and production. 
     have tried solving the problem by exploring in the internet but did not get a correct reason for this.
** Week 3[2017-12-11 Mon] to [2017-12-15 Fri]
*** Day 1[2017-12-11 Mon]
**** worklogs
 + Read the college cloud manual(i.e pdf given to us)
 + Setted the week targets 
 + Packaging of a js labs is the main target for the week
 + Installed apache2 on machines for js labs working
**** Install apache2
#+BEGIN_SRC : apache2.sh
sudo apt-get install apache2
#+END_SRC
**** Running apache2 server
#+BEGIN_SRC : apache2.sh
sudo systemctl start apache2
#+END_SRC
**** Stopping apache2 server
#+BEGIN_SRC : apache2.sh
sudo systemctl stop apache2
#+END_SRC
**** js labs
 + Got 31 js labs from [[https://gitlab.com/vlead-systems/experiment-server][Experiment-server]]
 + check the labs by running apache2 server and using url(localhost/lab_id)

*** Day 2[2017-12-12 Tue]
**** rpm
 + Many packages have been explored
 + rpm,deb are kept to be tried
 + exploration about rpm is done,setup is done from [[https://yannik520.github.io/rpm_on_ubuntu.html][rpm]]
**** Install rpm
#+BEGIN_SRC : rpm.sh
sudo apt install rpm
#+END_SRC
**** Create rpm build directory
#+BEGIN_SRC : rpm.sh
mkdir ~/rpmbuild
#+END_SRC
**** Create SOURCES AND SPECS directories in rpm build directory
#+BEGIN_SRC : rpm.sh
mkdir ~/rpmbuild/SOURCES ~/rpmbuild/SPECS
#+END_SRC
**** Place the Source of package inside the SOURCES directory
**** Create a SPEC file in SPECS directory
**** Create a SPEC file
#+BEGIN_SRC : rpm.sh
cd ~/rpmbuild/SPECS
rpmdev-newspec PackageName
#+END_SRC
**** Spec File Template can be seen from rpm link above.
**** Problems
 + As OS became a main factor, realized that rpm is for CentOS,FEDORA
 + As our packaging is for ubuntu 14.04
 + Realized to go for dpkg(deb) ,sice it is linux and ubuntu

*** Day 3[2017-12-13 Wed]
**** deb
 + deb has been explored
 + exploration is done from [[http://www.king-foo.com/2011/11/creating-debianubuntu-deb-packages/][deb]]
**** Creating the Package
#+BEGIN_SRC : deb.sh
sudo dpkg-deb --build PackageName
#+END_SRC
 + This Creates a PackageName.deb file
 + We can now install on any debain installation with following command
#+BEGIN_SRC : deb.sh
sudo dpkg -i PackegeName.deb
#+END_SRC
**** Sample Example for creating a package
***** Creating for hello
#+BEGIN_EXAMPLE
mkdir -p hello/DEBIAN
cd hello/DEBIAN
touch control
cd ..
mkdir-p usr/bin
cd usr/bin
vi hello.c
print hello in that
gcc hello.c -o hello
./hello         
cd
sudo apt-get install build-essential
sudo dpkg-deb --build hello/
sudo dpkg dpkg -i hello.deb
#+END_EXAMPLE
**** script of control file
#+BEGIN_EXAMPLE
package : hello
Version : 1.0.1
Section : base
Priority : optional
Architecture : all
Depends : debcont(>= 0.2.26)
Maintainer :
Description :
#+END_EXAMPLE
*** Day 4[2017-12-14 Thurs]
 + explored the debian packaging through references like Debian Packaging Tutorial by Lucas Nussbaum
 + explored through many sites for packaging purpose
 + conversion of flash to js are solved at the same time, molecular-spectroscopy and florescence lab were given to fix the errors
 + spectroscopy lab exp2,exp6,exp9 have errors on production.explored through the codes of lab . trying to fix them
*** Day 5[2017-12-15 Fri]
 + explored many sites for debian packaging
 + tried many ways for packaging but couldnt find the packaging similar to which we need for js labs.
 + tried to fix absorption spectroscopy lab issues by keeping common images at one folder.
 + as videos in exp2,exp6,exp9 couldnt load in production, tried different ways like other video formats .but resolve the issue
** Week 4 [2017-12-18 Mon] to [2017-12-22 Fri]
*** Day 1[2017-12-18 Mon]
 + debian packaging tutorials have been explored
 + computer organization lab issues have been raised on testing
 + 5 issues were raised,5 were solved.
*** Day 2[2017-12-19 Tue]
